- name: install packages using install
  hosts: web
  become: yes
  tasks:
    - name: install packages using loops concept in redhat machine
      ansible.bultin.dnf:
        name: "{{ item }}"
        state: installed
      loop:
      - gcc
      - mysql
      - git
      - zip
      when: ansible_os_family == "RedHat"

    - name: install packages using loops in ubuntu machine
      ansible.builtin.apt:
        name: "{{ item }}"
        state: installed
      loop:
      - gcc
      - mysql
      - git
      - zip
      when: ansible_os_family == "Debian"